version: '2'
services:
  memcached-idfa:
      image: memcached
      ports:
        - "33013:11211"

  memcached-gaid:
      image: memcached
      ports:
        - "33014:11211"
  memcached-adid:
      image: memcached
      ports:
        - "33015:11211"

  memcached-dvid:
      image: memcached
      ports:
        - "33016:11211"